const PAYMENT_STATUS = {
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  PENDING: "PENDING",
  INITIATED: "INITIATED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
};

const TOKENS = {
  FREE: 0,
  BASIC: 1000,
  PRO: 5000,
  PREMIUM: 10000,
  ULTRA: 20000,
};

const PRICE = {
  FREE: 0,
  BASIC: 100,
  PRO: 500,
  PREMIUM: 1000,
  ULTRA: 2000,
};

const PLAN_TYPE = {
  FREE: "FREE",
  BASIC: "BASIC",
  PRO: "PRO",
  PREMIUM: "PREMIUM",
  ULTRA: "ULTRA",
};

export { PAYMENT_STATUS, TOKENS, PLAN_TYPE, PRICE };
