enum RegionType {
  Lakshadweep = 2496,
  AndamanAndNicobarIslands = 2454,
  AndhraPradesh = 2486,
  ArunachalPradesh = 2487,
  Assam = 2513,
  Bihar = 2488,
  Chandigarh = 2489,
  Chhattisgarh = 2490,
  DadraAndNagarHaveliAndDamanAndDiu = 2492,
  Delhi = 2493,
  Goa = 2514,
  Gujarat = 2455,
  Haryana = 2193,
  HimachalPradesh = 2494,
  JammuAndKashmir = 2495,
  Jharkhand = 2515,
  Karnataka = 2485,
  Kerala = 2516,
  Ladakh = 14011,
  MadhyaPradesh = 2497,
  Maharashtra = 2517,
  Manipur = 2498,
  Meghalaya = 2499,
  Mizoram = 2500,
  Nagaland = 2501,
  Odisha = 2502,
  Puducherry = 2503,
  Punjab = 2504,
  Rajasthan = 2505,
  Sikkim = 2506,
  TamilNadu = 2507,
  Telangana = 2508,
  Tripura = 2509,
  Uttarakhand = 2511,
  UttarPradesh = 2510,
  WestBengal = 2512,
  India = 1362,
  Constitution = 1,
}

const regions = [
  {
    name: "Lakshadweep",
    id: RegionType.Lakshadweep,
    nameSpaceName: "Lakshadweep",
  },
  {
    name: "Andaman and Nicobar Islands",
    id: RegionType.AndamanAndNicobarIslands,
    nameSpaceName: "Andaman-and-Nicobar-Islands",
  },
  {
    name: "Andhra Pradesh",
    id: RegionType.AndhraPradesh,
    nameSpaceName: "Andhra-Pradesh",
  },
  {
    name: "Arunachal Pradesh",
    id: RegionType.ArunachalPradesh,
    nameSpaceName: "Arunachal-Pradesh",
  },
  { name: "Assam", id: RegionType.Assam, nameSpaceName: "Assam" },
  { name: "Bihar", id: RegionType.Bihar, nameSpaceName: "Bihar" },
  {
    name: "Chandigarh",
    id: RegionType.Chandigarh,
    nameSpaceName: "Chandigarh",
  },
  {
    name: "Chhattisgarh",
    id: RegionType.Chhattisgarh,
    nameSpaceName: "Chhattisgarh",
  },
  {
    nameSpaceName: "Dadra-and-Nagar-Haveli-and-Daman-and-Diu",
    name: "Dadra and Nagar Haveli and Daman and Diu",
    id: RegionType.DadraAndNagarHaveliAndDamanAndDiu,
  },
  { nameSpaceName: "Delhi", name: "Delhi", id: RegionType.Delhi },
  { nameSpaceName: "Goa", name: "Goa", id: RegionType.Goa },
  { nameSpaceName: "Gujarat", name: "Gujarat", id: RegionType.Gujarat },
  { nameSpaceName: "Haryana", name: "Haryana", id: RegionType.Haryana },
  {
    nameSpaceName: "Himachal-Pradesh",
    name: "Himachal Pradesh",
    id: RegionType.HimachalPradesh,
  },
  {
    nameSpaceName: "Jammu-and-Kashmir",
    name: "Jammu and Kashmir",
    id: RegionType.JammuAndKashmir,
  },
  { nameSpaceName: "Jharkhand", name: "Jharkhand", id: RegionType.Jharkhand },
  { nameSpaceName: "Karnataka", name: "Karnataka", id: RegionType.Karnataka },
  { nameSpaceName: "Kerala", name: "Kerala", id: RegionType.Kerala },
  { nameSpaceName: "Ladakh", name: "Ladakh", id: RegionType.Ladakh },
  {
    nameSpaceName: "Madhya-Pradesh",
    name: "Madhya Pradesh",
    id: RegionType.MadhyaPradesh,
  },
  {
    nameSpaceName: "Maharashtra",
    name: "Maharashtra",
    id: RegionType.Maharashtra,
  },
  { nameSpaceName: "Manipur", name: "Manipur", id: RegionType.Manipur },
  { nameSpaceName: "Meghalaya", name: "Meghalaya", id: RegionType.Meghalaya },
  { nameSpaceName: "Mizoram", name: "Mizoram", id: RegionType.Mizoram },
  { nameSpaceName: "Nagaland", name: "Nagaland", id: RegionType.Nagaland },
  { nameSpaceName: "Odisha", name: "Odisha", id: RegionType.Odisha },
  {
    nameSpaceName: "Puducherry",
    name: "Puducherry",
    id: RegionType.Puducherry,
  },
  { nameSpaceName: "Punjab", name: "Punjab", id: RegionType.Punjab },
  { nameSpaceName: "Rajasthan", name: "Rajasthan", id: RegionType.Rajasthan },
  { nameSpaceName: "Sikkim", name: "Sikkim", id: RegionType.Sikkim },
  { nameSpaceName: "Tamil-Nadu", name: "Tamil Nadu", id: RegionType.TamilNadu },
  { nameSpaceName: "Telangana", name: "Telangana", id: RegionType.Telangana },
  { nameSpaceName: "Tripura", name: "Tripura", id: RegionType.Tripura },
  {
    nameSpaceName: "Uttarakhand",
    name: "Uttarakhand",
    id: RegionType.Uttarakhand,
  },
  {
    nameSpaceName: "Uttar-Pradesh",
    name: "Uttar Pradesh",
    id: RegionType.UttarPradesh,
  },
  {
    nameSpaceName: "West-Bengal",
    name: "West Bengal",
    id: RegionType.WestBengal,
  },
  { nameSpaceName: "India", name: "India", id: RegionType.India },
  {
    nameSpaceName: "Constitution",
    name: "Constitution",
    id: RegionType.Constitution,
  },
];

export { regions, RegionType };
